### PR TITLE
updates. closes #1, closes #2, closes #4

### LINKED ISSUE #1: Remove Laser from the carousel leader section
Well since he is no longer in FCLM, maybe replace him with lordo on the website.

### LINKED ISSUE #2: Styling updates

### LINKED ISSUE #4: Make fonts https
google fonts are current http. OR make them local

### PR DESCRIPTION
**Pull request by mononz**
text now center aligned, laser removed from carousel, fonts are now https

### CODE REVIEW

**Review by Dalordish — APPROVED** [review]
Looks good.

**Review by Dalordish — APPROVED** [review]
All of the font links work, looks good to me.

**Review by Dalordish — APPROVED** [review]
Center looks much better then aligned to the left (tested with chrome debugger).

**Review by DylanNZL — APPROVED** [review]
👌

**Review by dhack8 — APPROVED** [review]

**Review by Peter-NZ — APPROVED** [review]

**Review by Peter-NZ — APPROVED** [review]

**Review by Peter-NZ — APPROVED** [review]

**Pull request merged**
